"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_controller_1 = require("../controllers/auth.controller");
const donor_controller_1 = require("../controllers/donor.controller");
const otp_controller_1 = require("../controllers/otp.controller");
const ngo_controller_1 = require("../controllers/ngo.controller");
const notifications_controller_1 = require("../controllers/notifications.controller");
const user_controller_1 = require("../controllers/user.controller");
const volunteer_controller_1 = require("../controllers/volunteer.controller");
const router = (0, express_1.Router)();
router.put('/update-user', user_controller_1.updateUser);
router.post('/register', auth_controller_1.signUp);
router.post('/refresh-token', auth_controller_1.refreshToken);
router.post('/send-otp', otp_controller_1.sendOtp);
router.post('/verify-otp', otp_controller_1.verifyOtp);
router.get('/get-donations', donor_controller_1.getDonations);
router.post('/new-donation', donor_controller_1.newDonation);
router.put('/accept-ngo-request', donor_controller_1.acceptNgoRequest);
router.put('/withdraw-ngo-request', donor_controller_1.withdrawNgoRequest);
router.post('/get-ngo-data', ngo_controller_1.getNgoData);
router.put('/ngo-accept-donation', ngo_controller_1.ngoAcceptDonation);
router.put('/ngo-withdraw-donation', ngo_controller_1.ngoWithdrawDonation);
router.get('/get-notifications', notifications_controller_1.getNotifications);
router.post('/add-notification', notifications_controller_1.addNotification);
router.delete('/remove-notification', notifications_controller_1.removeNotification);
router.put("/volunteer-accept-request", volunteer_controller_1.takeOrder);
router.put("/volunteer-deliver-request", volunteer_controller_1.deliverOrder);
exports.default = router;
